version: '3.8'

services:
  database:
    image: postgres
    container_name: database_rentalx
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres

  redis:
    image: redis:alpine
    container_name: redis_rentalx
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  app:
    build: .
    container_name: rentalx
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
      - redis
    depends_on:
      - database
      - redis

volumes:
  pgdata:
    driver: local
  cache:
    driver: local
